version: "3.8"

services:
  db:
    image: postgres:17.0 # Removed incorrect `-`
    container_name: postgres_db
    restart: always # Ensures the database restarts if it crashes
    ports:
      - "5432:5432" # Fixed indentation and removed extra `-`
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Use environment variables
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
